# Generated by Django 5.2.13 on 2026-05-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='value',
        ),
        migrations.AlterField(
            model_name='answer',
            name='value',
            field=models.CharField(default='default answer', max_length=1024, unique=True),
        ),
    ]
