# Generated by Django 5.2.13 on 2026-05-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_question_value_alter_answer_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='picked',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='answered_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddConstraint(
            model_name='answer',
            constraint=models.UniqueConstraint(fields=('value', 'question'), name='unique_question_answer'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('value',), name='unique_question'),
        ),
    ]
