# Generated by Django 5.2.13 on 2026-05-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_answer_picked_question_answered_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered_count',
        ),
    ]
