# Generated by Django 5.2.13 on 2026-05-07 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_remove_question_answered_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='responses',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
