# Generated by Django 5.2.13 on 2026-05-08 14:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_responses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='respondents',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
